[2024-03-03T01:53:34.307+0530] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.compute_averages manual__2024-03-02T19:24:10.303999+00:00 [queued]>
[2024-03-03T01:53:34.308+0530] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.compute_averages manual__2024-03-02T19:24:10.303999+00:00 [queued]>
[2024-03-03T01:53:34.309+0530] {taskinstance.py:2193} INFO - Starting attempt 28 of 29
[2024-03-03T01:53:34.312+0530] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): compute_averages> on 2024-03-02 19:24:10.303999+00:00
[2024-03-03T01:53:34.316+0530] {standard_task_runner.py:60} INFO - Started process 33224 to run task
[2024-03-03T01:53:34.319+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'weather_data_pipeline', 'compute_averages', 'manual__2024-03-02T19:24:10.303999+00:00', '--job-id', '361', '--raw', '--subdir', 'DAGS_FOLDER/Data_analysis.py', '--cfg-path', '/var/folders/th/tnjyp6yd1cj78nysn5t4jl6h0000gn/T/tmphed0qaau']
[2024-03-03T01:53:34.319+0530] {standard_task_runner.py:88} INFO - Job 361: Subtask compute_averages
[2024-03-03T01:53:34.333+0530] {task_command.py:423} INFO - Running <TaskInstance: weather_data_pipeline.compute_averages manual__2024-03-02T19:24:10.303999+00:00 [running]> on host aniks-macbook-air.local
[2024-03-03T01:53:34.348+0530] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='compute_averages' AIRFLOW_CTX_EXECUTION_DATE='2024-03-02T19:24:10.303999+00:00' AIRFLOW_CTX_TRY_NUMBER='28' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-02T19:24:10.303999+00:00'
[2024-03-03T01:53:34.362+0530] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/airflow/dags/Data_analysis.py", line 77, in compute_monthly_averages
    monthly_averages = (data | beam.Map(lambda x: x.groupby('DATE').mean()))
                        ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/apache_beam/transforms/ptransform.py", line 616, in __ror__
    replacements = {
                   ^
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/apache_beam/transforms/ptransform.py", line 617, in <dictcomp>
    id(v): p | 'CreatePInput%s' % ix >> Create(v, reshuffle=False)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/apache_beam/transforms/core.py", line 3718, in __init__
    raise TypeError(
TypeError: PTransform Create: Refusing to treat string as an iterable. (string=b'\x80\x04\x95:\x00\x00\x00\x00\x00\x00\x00\x8c\x12apache_beam.pvalue\x94\x8c\x1c_InvalidUnpickledPCollection\x94\x93\x94)R\x94.')
[2024-03-03T01:53:34.366+0530] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_data_pipeline, task_id=compute_averages, execution_date=20240302T192410, start_date=20240302T202334, end_date=20240302T202334
[2024-03-03T01:53:34.369+0530] {standard_task_runner.py:107} ERROR - Failed to execute job 361 for task compute_averages (PTransform Create: Refusing to treat string as an iterable. (string=b'\x80\x04\x95:\x00\x00\x00\x00\x00\x00\x00\x8c\x12apache_beam.pvalue\x94\x8c\x1c_InvalidUnpickledPCollection\x94\x93\x94)R\x94.'); 33224)
[2024-03-03T01:53:34.375+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-03T01:53:34.380+0530] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
